[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.10", features = ["web"] }

# WebAssembly Debug
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
log = "0.4.34"
js-sys = "0.3.106"
wasm-bindgen = "0.2.129"
serde_json = "1"
web-sys = { version = "0.3.105", features = ["DedicatedWorkerGlobalScope", "Document", "Element", "ErrorEvent", "Event", "HtmlElement", "HtmlInputElement", "Location", "MessageEvent", "Performance", "Window", "Worker", "WorkerOptions", "WorkerType"] }

[features]
search-worker = []

[[bin]]
name = "sudoku_search_worker"
path = "src/bin/sudoku_search_worker.rs"
required-features = ["search-worker"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
